274 csv parser
UoaWDCC/nzpmc-exam-portal pull request #299
Opened 2023-05-10 12:31 UTC by ardo715

**Issue**

Need to be able to parse through X amount of students from csv into the front end

Closes #274 

**Solution**

Made a parseCSV function with a test script. The function also does integrity checks on the data being parsed.

**Discussion**
Merged master into the branch so should not be many conflicts

Currently the function will error if there is an invalid student in the csv file. This should be updated to create all the other students, and return a log of students that were unable to be created.

Currently uses a student class defined in the utils. This should be changed in the future to use the compatible types

**Risk**

No risk, all files are newly created.
Might have a problem with yarn / npm update as this uses the module csv-parse (npm install csv-parse)

**Reviewers**
@johnchen383 
@luorixo

2023-05-10 21:47 UTC, bcho892 reviewed
Looks good in terms of functionality and catches errors properly, however I think this could be done using typescript types instead of classes so the code is shorter:

```
type Student = {
  firstName: string;
  middleName: string;
  surname: string;
  email: string;
  yearLevel: number;
  heardFrom: string;
  reasonForTaking: string;
  teacherCode: string;
  teacherName: string;
  teacherEmail: string;
  schoolName: string;
  schoolAddress: string;
  phoneNumber: string;
  teacherCategory: string;
  island: Island;
  city: string;
};
``` 
and then it would be the same after, but you just say that:

```
const student: Student = {
  firstName: record.StudentFirstName,
  middleName: record.StudentMiddleName,
  surname: record.StudentSurname,
  email: record.StudentEmail,
  yearLevel: parseInt(record.StudentYearLevel),
  heardFrom: record.HeardFrom,
  reasonForTaking: record.ReasonForTaking,
  teacherCode: record.TeacherCode,
  teacherName: record.TeacherName,
  teacherEmail: record.TeacherEmail,
  schoolName: record.SchoolName,
  schoolAddress: record.SchoolAddress,
  phoneNumber: record.PhoneNumber,
  teacherCategory: record.TeacherCategory,
  island: record.Island as Island,
  city: record.City,
};
```
then like before:

```
students.push(student)
```
Also note that you won't need to call 
```
students.getAttributes
```
anymore and can just do 

```
console.log(students)
```

2023-05-11 21:16 UTC, bcho892 approved these changes
LGTM good job

2023-05-13 09:36 UTC, johnchen383 requested changes
Great work. Some minor changes requested. I also not that there's no package.json file committed. Where is that change?

2023-05-13 09:36 UTC, johnchen383 commented on client/src/utils/csv_parser.ts
> +import {parse} from '../../../node_modules/csv-parse';
you shouldn't have to reference a package like this. Does `import {parse} from 'csv-parse'` not work?

2023-05-13 09:36 UTC, johnchen383 commented on client/src/utils/csv_parser.ts
> +// Student object that can be accessed
Could you add a `TODO:` comment to note that this type will be eventually be replaced with a DTO class as defined in `common`

2023-05-13 09:36 UTC, johnchen383 commented on client/src/utils/csv_parser.ts
> +}
awesome stuff

2023-05-13 12:34 UTC, johnchen383 requested changes
Thanks for those changes. Just one thing to fix up :))

2023-05-13 12:34 UTC, johnchen383 commented on package.json
> +    "dependencies": {
update to package.json should be done in client one as not all modules depend on this.

2023-05-13 13:26 UTC, johnchen383 approved these changes
Lgtm

2023-05-13 13:39 UTC, merged