292 csv writing
UoaWDCC/nzpmc-exam-portal pull request #301
Opened 2023-05-14 23:21 UTC by else861

**Issue**
Need to receive data from the csv parser and write it onto a new csv file. 

Closes #[292]

**Solution**
Made a generateCsvFile function with a following test script.  The function transfers the data onto a new csv file and saves it into the user's directory.  

**Discussion**
Currently the function has a hardcoded file path. This should be updated to show a popup message to the user when they download the csv file. 

**Risk**
No risk, all files are newly created

**Reviewers**
@ardo715 
@johnchen383

2023-05-14 23:24 UTC, johnchen383 requested changes

2023-05-14 23:24 UTC, johnchen383 commented on package.json
> +    "packageManager": "yarn@1.22.19",
Remove dependency plz

2023-05-14 23:48 UTC, johnchen383 approved these changes

2023-05-21 22:42 UTC, ardo715 approved these changes
LGTM

2023-05-21 22:42 UTC, merged