fix: Implemented Erica's fix on validating phone number
UoaWDCC/nzpmc-exam-portal pull request #315
Opened 2023-05-21 12:24 UTC by ardo715

**Issue**

Phone Number validation was not always working

Closes #274 

**Solution**

Implemented Erica's solution to validate phone number
Checks for +64 and if its between 9 and 11 digits

**Risk**

No risk

**Reviewers**

@johnchen383 
@engi850

2023-05-21 22:22 UTC, johnchen383 requested changes
nice work. look at the comments

2023-05-21 22:22 UTC, johnchen383 commented on client/src/utils/csv_parser.ts
> +    phoneNumber = phoneNumber.replace('+64', '0');
edge case where u have +64[11-digit number]. Then this will be 12, and then fail the check?

2023-05-21 22:22 UTC, johnchen383 commented on client/src/utils/csv_parser.ts
> +    return true;
would also trim the phone number `phoneNumber.trim()` to remove leading and trailing whitespaces. For instance, if there is '+64 [number]' then they'll be the additional space after you strip off the +64

2023-07-08 11:27 UTC, Oculux314 commented
Heya has this been merged in elsewhere? I think this might've been missed.

2023-07-09 00:57 UTC, Oculux314 commented
Hey this merge contains the commits I accidentally pushed to main (reverted now).
Main things are adding csv parser scripts into package.json and adding .csv to gitignore, tagging on to save a review or two!

2023-07-20 03:36 UTC, closed without merging