420 submit on last question
UoaWDCC/nzpmc-exam-portal pull request #442
Opened 2023-09-28 02:52 UTC by else861

**Issue**
No submit button for the last question

Closes #420 

**Solution**
Created a "Submit Exam" button that is only displayed on the last question by creating a function that checks if the current question is the last question (isLastQuestion() line 116 in index.vue). The rest of the questions have a "Next Question" button. 

**Risks**
None

**Reviewers**
@ardo715 
@bcho892

2023-09-28 03:03 UTC, bcho892 requested changes
please implement aaron's logic

2023-09-28 03:07 UTC, bcho892 approved these changes

2023-09-28 10:58 UTC, Oculux314 commented
![image](https://github.com/UoaWDCC/nzpmc-exam-portal/assets/121474948/59f951e3-aeca-403c-8fd6-bb8156078186)
---
![image](https://github.com/UoaWDCC/nzpmc-exam-portal/assets/121474948/85bce639-85d7-493c-b9df-8356259c97eb)

+1

2023-09-30 13:09 UTC, ardo715 approved these changes
LGTM, thanks for using my logic = )

2023-09-30 13:11 UTC, merged