feat: Added cascading deletion when deleting an exam to all user quizzes
UoaWDCC/nzpmc-exam-portal pull request #445
Opened 2023-09-28 04:48 UTC by ardo715

**Issue**

Deleting an exam did not delete associated user quizzes

Closes #ticket_num

**Solution**
Implemented cascading deletion upon deletion of an exam

It works

**Risks**

might delete all exams idk

**Reviewers**

@else861 @Oculux314

2023-09-28 04:48 UTC, else861 approved these changes
looks amazing

2023-09-28 05:20 UTC, Oculux314 commented
Wow if it were done 15min earlier you coulda been in contention with Sophie for faster PR raised this year 😁

Will check it out tonight, busy rn~

2023-09-28 09:44 UTC, Oculux314 requested changes
Looks great, as far as I can tell.
Reviewing these are actually so great for learning (I would Not have been able to do this on my own).

Flagged a listing issue and some unneeded logs. Requesting changes because of the linting, but the cl stuff will be picked up in another ticket if you don't fix it here :)

2023-09-28 09:44 UTC, Oculux314 commented on client/src/utils/quizManagement.ts
> +    const deleteExamMutation = await apollo.mutate({
ESLint is throwing a tantrum since deleteExamMutation is not used

2023-09-28 09:44 UTC, Oculux314 commented on client/src/utils/quizManagement.ts
> +    console.log(deleteUserQuizzesMutation.data)
Do we need these logs?

2023-09-28 09:44 UTC, Oculux314 commented on service/src/controllers/userQuiz.ts
> +        console.log(userQuizzesPack)
(Also this one)

2023-09-30 03:49 UTC, Oculux314 approved these changes
Beautiful~

2023-09-30 13:02 UTC, merged