Submit exam upon timeout
UoaWDCC/nzpmc-exam-portal pull request #451
Opened 2023-10-01 05:06 UTC by alexmingikim

**Issue**

Exam was not submitting even after time out 

Closes #385

**Solution**

See if time has run out and if so, automatically submits 

**Discussion**

As part of the solution (see lines 114-133 TopbarTimer.vue), I've reused the submit logic i.e. the submitQuiz() method from Sidebar.vue. Would it be preferable to just call this method from TopbarTImer.vue? Wasn't sure how to do this. 

**Risks**

None.

However, I noticed that when the timer starts it doesn't start from the exact time given. For example if the exam was a minute long, the timer doesn't start from 1 min but starts from ~58secs. I'm not sure whether this problem has occurred throughout or just an issue with my branch. A confirmation would be nice :)

**Reviewers**

@Oculux314
@bcho892

2023-10-01 10:29 UTC, Oculux314 commented
Updated the timer by merging in main and also made it fit nicely in the sidebar
Requested review from Aaron cause I've now made code changes and he was interested ✨

2023-10-01 10:30 UTC, Oculux314 commented
Updated the timer by merging in main and also made it fit nicely in the sidebar
Requested review from Aaron cause I've now made code changes and he was interested ✨

(Looks good btw Alex, love the addition!)

2023-10-07 07:45 UTC, bcho892 requested changes
small error spotted thats causing submitting glitch

2023-10-07 07:45 UTC, bcho892 commented on client/src/components/app/exam/TopbarTimer.vue
> +        this.examStore.submitting = true
you need to set this flag back to 'false' or it will always say submitting. The other fix we could do is on load of the exams page we reset this flag

2023-10-11 02:14 UTC, alexmingikim commented
![30540F1D-2AB5-43A9-8A6D-97A1CF6BF981_1_102_o](https://github.com/UoaWDCC/nzpmc-exam-portal/assets/109945626/460b3a24-3038-4ce0-8bfb-991859250454)

2023-10-11 02:18 UTC, alexmingikim commented
![ezgif com-video-to-gif](https://github.com/UoaWDCC/nzpmc-exam-portal/assets/109945626/30aea7b9-0998-468f-a3d3-762ad468b377)

2023-10-16 23:06 UTC, bcho892 approved these changes

2023-10-17 21:49 UTC, bcho892 commented
I got this branch working on #451 should be ok now just check again

2023-10-18 02:54 UTC, luorixo approved these changes
Looks good!

2023-10-18 02:54 UTC, merged