Hotfix latex
UoaWDCC/nzpmc-exam-portal pull request #455
Opened 2023-10-05 03:28 UTC by bcho892

**Issue**

Small bug where latex didnt work on exam editor

2023-10-05 05:41 UTC, johnchen383 requested changes

2023-10-05 05:41 UTC, johnchen383 commented on client/src/components/app/DisplayText.vue
> +          console.log('fuck all here')
remove plz ahah

2023-10-05 08:09 UTC, bcho892 commented
LOL

2023-10-05 08:09 UTC, bcho892 commented
was a feature trust

2023-10-07 18:56 UTC, johnchen383 approved these changes

2023-10-10 11:45 UTC, Oculux314 approved these changes
lgtm!

2023-10-11 10:07 UTC, merged